core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('L', 'Likes'),
    ('F', 'Followers'),
    ('V', 'Views'),
    ('C', 'Comments'),
    ('A', 'Auto')
)


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
  
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/checkout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Add meta tags for mobile and IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>BoostMyInsta</title>
    {% load static %}
  </head>
  <center>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="footer_content text-center">
            <a href="/">
              <img src="{% static 'assets/images/logo.png' %}" alt="Logo" />
            </a>
          </div>
        </div>
      </div>
    </div>
    <body>
      <!-- Set up a container element for the button -->
      <div id="paypal-button-container"></div>

      <!-- Include the PayPal JavaScript SDK -->
      <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

      <script>
        // Render the PayPal button into #paypal-button-container
        paypal
          .Buttons({
            // Set up the transaction
            createOrder: function (data, actions) {
              return actions.order.create({
                purchase_units: [
                  {
                    amount: {
                      value: '88.44',
                    },
                  },
                ],
              })
            },

            // Finalize the transaction
            onApprove: function (data, actions) {
              return actions.order.capture().then(function (orderData) {
                // Successful capture! For demo purposes:
                console.log(
                  'Capture result',
                  orderData,
                  JSON.stringify(orderData, null, 2),
                )
                var transaction =
                  orderData.purchase_units[0].payments.captures[0]
                alert(
                  'Transaction ' +
                    transaction.status +
                    ': ' +
                    transaction.id +
                    '\n\nSee console for all available details',
                )

                // Replace the above to show a success message within this page, e.g.
                // const element = document.getElementById('paypal-button-container');
                // element.innerHTML = '';
                // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                // Or go to another URL:  actions.redirect('thank_you.html');
              })
            },
          })
          .render('#paypal-button-container')
      </script>
    </body>
  </center>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<main>
  <div class="container">

    <!--Navbar-->
 <CENTER>{% include "navbar1.html" %}</CENTER>
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3  pt-115 pb-120">

      <!-- Navbar brand -->
      <span class="navbar-brand"></span>

      <!-- Collapse button -->


      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav nav-item sub-menu ">
          <li class="nav-item active">
            <br>
          </li>
          <li class="nav-item">
            <a class="" href="#">

            </a>
          </li>
          <li class="nav-item">
            <a class="" href="#">

            </a>
          </li>
          <li class="nav-item">
            <a class="" href="#">

            </a>
          </li>
          <li class="nav-item">
            <a class="" href="#">

            </a>
          </li>

          <br>
          <li class="nav-item">
            <a class="" href="/">
              <font color="#ffcc001">Likes</font>
            </a>
          </li>
          <li class="nav-item">
            <a class="" href="/?page=2">
              <font color="#ffcc01">Followers</font>
            </a>
          </li>
          <li class="nav-item">
            <a class="" href="/?page=3">
              <font color="#ffcc001">Views</font>
            </a>
          </li>
          <li class="nav-item">
            <a class="" href="/?page=4">
              <font color="#ffcc01">Comments</font>
            </a>
          </li>
          <li class="nav-item">
            <a class="" href="/?page=5">
              <font color="#ffcc01">Auto</font>
            </a>
          </li>

        </ul>
        <br>
        <br>
        <!-- Links -->


      </div>
      <!-- Collapsible content -->

    </nav>

    <!--/.Navbar-->
    <style>
      p.round3 {
        border: 2px solid #ffcc01;
        border-radius: 12px;
        padding: 5px;
      }
    </style>
    <!--Section: Products v.3-->
    <section class="text-center mb-3">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <a href="{{ item.get_absolute_url }}">
          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="{{ item.image.url }}" class="card-img-top" {% endcomment %} <img
                src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <strong>
              <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                <span class="badge badge-pill {{ item.get_label_display }}-color"></span>
              </a>
            </strong>
            <p>
              <a href="{{ item.get_absolute_url }}">
            <font color="#333"> 100% Real Users<br>
            No Password Required<br>
            24/7 Support</font>
          </a></p>
          <div class="card-body text-center">
            <a href="{{ item.get_absolute_url }}">
              <h4 class="font-weight-bold black-text ">
                  <p class="round3">
                      <strong>$
                        {% if item.discount_price %}
                        {{ item.discount_price }}
                        {% else %}
                        {{ item.price }}
                        {% endif %}
                      </strong>

                  </p>
              </h4>

            </a>
          </div>
          </div>
        </a>
        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->



  </div>
</main>

{% endblock content %}

templates/log.html
{% extends "account/base.html" %}
{% load i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
  <main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
          <h1>{% trans "Sign In" %}</h1>

          {% get_providers as socialaccount_providers %}

          {% if socialaccount_providers %}
          <p>{% blocktrans with site.name as site_name %}Please sign in with one
          of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
          for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

          <div class="socialaccount_ballot">

            <ul class="socialaccount_providers">
              {% include "socialaccount/snippets/provider_list.html" with process="login" %}
            </ul>

            <div class="login-or">{% trans 'or' %}</div>

          </div>

          {% include "socialaccount/snippets/login_extra.html" %}

          {% else %}
          <p>{% blocktrans %}If you have not created an account yet, then please
          <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
          {% endif %}

          <form class="login" method="POST" action="{% url 'account_login' %}">
            {% csrf_token %}
            {{ form|crispy }}
            {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <a class="btn btn-default" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
            <button class="btn btn-primary" type="submit">{% trans "Sign In" %}</button>
          </form>
          </div>
        </div>
      </section>
    </div>
  </main>

{% endblock %}

templates/navbar.html
{% load static %}


<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="/">
    <img src="{% static 'assets/images/logo.png' %}" alt="Logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="toggler-icon"></span>
    <span class="toggler-icon"></span>
    <span class="toggler-icon"></span>

  </button>
  <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
    <ul id="nav" class="navbar-nav ml-auto">

      <li class="nav-item active">
        <a class="" href="{% url 'core:order-summary' %}">Cart<span></span></a>
      </li>
      <li class="nav-item">
        <a class="" href="{% url 'account_logout' %}">Log Out<span></span></a>
      </li>

      <li class="nav-item">
        <a class="" href="{% url 'account_login' %}">Sign In<span></span></a>
      </li>
      <li class="nav-item ">
        <a class="" href="{% url 'account_signup' %}">Sign Up <span></span></a>
      </li>




    </ul>
  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total }}</strong>
        </li>
    </ul>


    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% load static %} {% block content %}
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>{% block head_title %}BoostMyInsta{% endblock %}</title>
{% block extra_head %} {% endblock %}

<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
/>
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script>
  // Render the PayPal button into #paypal-button-container
  paypal
    .Buttons({
      // Set up the transaction
      createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: [
            {
              amount: {
                value: '88.44',
              },
            },
          ],
        })
      },

      // Finalize the transaction
      onApprove: function (data, actions) {
        return actions.order.capture().then(function (orderData) {
          // Successful capture! For demo purposes:
          console.log(
            'Capture result',
            orderData,
            JSON.stringify(orderData, null, 2),
          )
          var transaction = orderData.purchase_units[0].payments.captures[0]
          alert(
            'Transaction ' +
              transaction.status +
              ': ' +
              transaction.id +
              '\n\nSee console for all available details',
          )

          // Replace the above to show a success message within this page, e.g.
          // const element = document.getElementById('paypal-button-container');
          // element.innerHTML = '';
          // element.innerHTML = '<h3>Thank you for your payment!</h3>';
          // Or go to another URL:  actions.redirect('thank_you.html');
        })
      },
    })
    .render('#paypal-button-container')
</script>
<link href="{% static 'assets/css/animate.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/slick.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/lineicons.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/default.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="footer_content text-center">
        <a href="/">
          <img src="{% static 'assets/images/logo.png' %}" alt="Logo" />
        </a>
        <ul class="footer_social"></ul>
      </div>
    </div>
  </div>
</div>
<main>
  <div class="container">
    <div class="table-responsive text-nowrap">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>

            <th scope="col">Total Item Price</th>
            <th scope="col">Post Link</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
              <a
                href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"
              >
                <i class="fas fa-minus mr-2"></i>
              </a>
              {{ order_item.quantity }}
              <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                <i class="fas fa-plus ml-2"></i>
              </a>
            </td>
            <td>
              {% if order_item.item.discount_price %} ${{
              order_item.get_total_discount_item_price }}
              <span class="badge badge-primary">
                Saving ${{ order_item.get_amount_saved }}
              </span>
              {% else %} ${{ order_item.get_total_item_price }} {% endif %}
              <a
                style="color: red;"
                href="{% url 'core:remove-from-cart' order_item.item.slug %}"
              >
                <i class="fas fa-trash float-right"></i>
              </a>
            </td>
            <td>
              <div>
                <input
                  type="text"
                  id="uname"
                  name="Username"
                  placeholder="@Link Post"
                />
              </div>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">Your cart is empty</td>
          </tr>
          <tr>
            <td colspan="5">
              <a class="btn btn-primary float-right" href="/">
                Continue shopping
              </a>
            </td>
          </tr>
          {% endfor %} {% if object.coupon %}
          <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
          </tr>
          {% endif %} {% if object.get_total %}
          <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
          </tr>
          <tr>
            <td colspan="5">
              <div id="paypal-button-container"></div>

              <a class="btn btn-primary float-right" href="/">
                Continue shopping
              </a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</main>

{% endblock content %}

templates/product.html
{% block content %} {% load static %}
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>{% block head_title %}BoostMyInsta{% endblock %}</title>
{% block extra_head %} {% endblock %}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"/>
<link href="{% static 'assets/css/animate.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/slick.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/lineicons.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/default.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
<section class="header_area">
  <div class="header_navbar">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="/">
              <img src="{% static 'assets/images/logo.png' %}" alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>

            </button>
            <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
              <ul id="nav" class="navbar-nav ml-auto">

                <li class="nav-item active">
                  <a class="" href="{% url 'core:order-summary' %}"><font color="#ffcc01">Cart</font><span></span></a>
                </li>
                <li class="nav-item">
                  <a class="" href="{% url 'account_logout' %}"><font color="#ffcc01">Log Out</font><span></span></a>
                </li>

                <li class="nav-item">
                  <a class="" href="{% url 'account_login' %}"><font color="#ffcc01">Sign In</font><span></span></a>
                </li>
                <li class="nav-item ">
                  <a class="" href="{% url 'account_signup' %}"><font color="#ffcc01">Sign Up </font><span></span></a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>

</section>

<main class="mt-5 pt-4">

  <div class="container dark-grey-text mt-5">
    <!--Grid row-->

    <div class="row wow fadeIn">
      <!--Grid column-->

      <div class="col-md-6 mb-4">
        <img src="{{ item.image.url }}" class="img-fluid" alt="" />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <!--Content-->
        <div class="p-4">
          <div class="mb-3">
            <a href="">
              <h2>
                <span class="badge purple mr-1">
                  {{ object.get_category_display }}
                </span>
              </h2>
            </a>
          </div>

          <p class="lead">
            {% if object.discount_price %}
            <span class="mr-1">
              <del>${{ object.price }}</del>
            </span>
            <span>${{ object.discount_price }}</span>
            {% else %}
            <span>${{ object.price }}</span>
            {% endif %}
          </p>

          <p class="lead font-weight-bold">{{ item.title }}</p>

          <p>{{ object.description }}</p>

          {% comment %}
          <form class="d-flex justify-content-left">
            <!-- Default input -->

            <input
              type="number"
              value="1"
              aria-label="Search"
              class="form-control"
              style="width: 100px;"
            >
            <button class="btn btn-primary btn-md my-0 p" type="submit">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>
          </form>
          {% endcomment %}
          <a
            href="{{ object.get_add_to_cart_url }}"
            class="btn btn-primary btn-md my-0 p"
          >
            Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
          <a
            href="{{ object.get_remove_from_cart_url }}"
            class="btn btn-danger btn-md my-0 p"
          >
            Remove from cart
          </a>
        </div>
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <hr />

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">Additional information</h4>

        <p></p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">
        <a href="/">
          <img
            src="{% static 'assets/images/like.png' %}"
            class="img-fluid"
            alt=""
          />
        </a>
        <center>
          <a href="/">
            <h4 class="my-4 h4">Likes</h4>
          </a>
        </center>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <a href="/?page=2">
          <img
            src="{% static 'assets/images/fol.png' %}"
            class="img-fluid"
            alt=""
          />
        </a>
        <center>
          <a href="/?page=2">
            <h4 class="my-4 h4">Followers</h4>
          </a>
        </center>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <a href="/?page=3">
          <img
            src="{% static 'assets/images/view.png' %}"
            class="img-fluid"
            alt=""
          />
        </a>
        <center>
          <a href="/?page=3">
            <h4 class="my-4 h4">Views</h4>
          </a>
        </center>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
</main>

{% endblock content %}
{% include "footer.html" %}
{% include "scripts.html" %}

{% block extra_scripts %}
{% endblock extra_scripts %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

